apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - n8n-namespace.yaml
  - n8n-serviceaccount.yaml
  - n8n-scc.yaml
  - n8n-configmap.yaml
  - n8n-secret.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-route.yaml
  # PostgreSQL
  - postgres/kustomization.yaml
  # Remove or comment out if not using private registry
  # - quay-io-dkcapgemini-image-pull.yaml